#!/bin/bash

SKETCHYBAR_HOME="$HOME/.config/sketchybar"
ITEM_DIR="$SKETCHYBAR_HOME/items"
PLUGIN_DIR="$SKETCHYBAR_HOME/plugins"

FONT="JetBrainsMono Nerd Font"

BAR_PADDING=4
ICON_LABEL_PADDING=4
ITEM_PADDING=12
GROUP_PADDING=8
CORNER_RADIUS=16